services:

  backend:
    build: ./backend
    image: primaria_backend:latest
    container_name: primaria_backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: deploy
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENTE_ID: ${GOOGLE_CLIENTE_ID}
      GOOGLE_CLIENTE_SECRETO: ${GOOGLE_CLIENTE_SECRETO}
    networks:
      - primaria_net

  frontend:
    build: ./frontend
    image: primaria_frontend:latest
    container_name: primaria_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - primaria_net

networks:
  primaria_net:
    external: true
    name: primaria_primaria_net