CREATE DATABASE IF NOT EXISTS primaria_db;
USE primaria_db;

CREATE TABLE usuarios (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  rol VARCHAR(50) NOT NULL,
  fecha_creacion DATETIME NOT NULL
);

CREATE TABLE whitelist (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(150) NOT NULL UNIQUE,
  fecha_alta DATETIME NOT NULL
);

CREATE TABLE casos_clinicos (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  estado VARCHAR(30) NOT NULL,
  fecha DATETIME NOT NULL
);
