# LOCAL SIN LOGING, PARA DESARROLLO CON LIVE-SERVER DE VISUAL STUDIO CODE (O SIMILAR)
app:
  security:
    dev-mode: false
  frontend-url: http://127.0.0.1:5500/frontend

server:
  servlet:
    session:
      cookie:
        same-site: None
        secure: true
        http-only: true


# # Seguridad relajada para desarrollo
# app:
#   security:
#     dev-mode: true

#   # URL del frontend para CORS y redirecciones en desarrollo local con live-server de Visual Studio Code
#   frontend-url: http://127.0.0.1:5500/frontend

# server:
#   servlet:
#     session:
#     # Configuración de cookies para desarrollo local 
#       cookie:
#         same-site: None
#         secure: false
#         http-only: true